-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 13, 2025 at 02:55 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `flower_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `flower_product`
--

CREATE TABLE `flower_product` (
  `product_id` int(10) NOT NULL,
  `product_name` varchar(100) DEFAULT NULL,
  `product_category` varchar(100) DEFAULT NULL,
  `product_desc` text NOT NULL,
  `price` float DEFAULT NULL,
  `stock` int(20) DEFAULT NULL,
  `image` blob DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `flower_product`
--

INSERT INTO `flower_product` (`product_id`, `product_name`, `product_category`, `product_desc`, `price`, `stock`, `image`) VALUES
(1, 'Scarlet Heaven Itoh Peony', 'PEONIES', 'This is one of the best red Itoh peonies we\'ve found. Its huge flowers have deep scarlet petals and golden-yellow anthers—fabulous in fresh floral arrangements. Itoh peonies combine the best peony traits. They were originated by crossing herbaceous and tree peonies. The result is a dense, rounded plant only 2-3\' tall and wide, with a great abundance of large 7-9\" blooms. They are borne on strong, non-flopping stems atop handsome foliage that stays attractive all season. Even better, once they mature, they bloom weeks longer than either parent, producing more than 50 blooms over an extended six-week period from late spring into early summer. And they take more heat and cold, extending the area in which peonies can be enjoyed as far south as Atlanta, where they are reported to do well if given afternoon shade and water in dry spells. Deer tend to avoid. Paeonia x \'Scarlet Heaven\'\r\n\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 171500, 20, 0x6173736574732f696d672f70726f64756374312e77656270),
(2, 'Oochigeas Itoh Peony', 'PEONIES', 'Itoh peonies are a treasure of hybridization, showing off the attractive plant habit of herbaceous peonies and the massive, gorgeous flowers of tree peonies. Itoh varieties are difficult to obtain, however, so we are delighted to have new varieties to offer—especially when that new variety is as special as Oochigeas. This peony produces boatloads of gorgeous, rounded and fully double blooms, in an unexpected, interesting color combination. The blooms appear in late spring, on a medium-sized bush. Lush foliage will keep the plant handsome for months after the blooms have finished. Peonies can last for decades in the garden, so it would make a great foundation plant. You could also put it in a perennial border or cutting garden. This peony\'s name, Oochigeas, is in reference to a young woman in an Algonquian legend that\'s similar to Cinderella.Paeonia itoh\'Oochigeas\'\r\n\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 206500, 10, 0x6173736574732f696d672f70726f64756374322e77656270),
(7, 'Lincoln Hybrid Tea Rose', 'ROSES', 'This American hybrid tea rose was a breakthrough when it was first introduced in 1965, and it\'s still hard to compete with its classic beauty today. Their form is large and fully double, with an irresistible damask fragrance. Mister Lincoln provides a full, deep green background in a rose garden, and strong straight stems for easy cutting. Rosa hybrida \'Mister Lincoln\'', 206500, 30, 0x6173736574732f696d672f626573742d73656c6c6572322e77656270),
(8, 'Clematis Poet', 'CLEMATIS & VINES', 'Allow Clematis Poet to put your garden in perfect harmony with its purple-blue, double-blooming flowers. Poet features large flowers on a medium plant, and has quickly earned a spot among our favorite later large-flowering Clematis. One reason is its rare form in combination with \"green prune\" needs. You won\'t find another fully-double Clematis that blooms on new vines –but Poet is living proof that Clematis can be both simple to grow and breathtaking to observe.\r\n\r\nGorgeous flowers open wide, with sepals stacked atop each other. Periwinkle blue tones pair beautifully with bright, light-colored centers--there aren\'t enough words to describe the unique elegance of this Clematis. Try pairing Poet with Clematis Maria Curie Slodowski, contrasting beautifully with Maria\'s puffy, white flowers. Poet is free blooming, and blooms more quickly than most double Clematis. The new genetics behind this plant are truly on track to change the game of Clematis gardening. In Europe, where this plant is sold as Clematis \'Floral Dance,\' it\'s attracting the attention of Clematis lovers looking for cutting-edge cultivars. This is a Spring Hill exclusive in the United States, so make sure to secure this incredible Clematis for your own garden. Clematis \'Floral Dance\'\r\n\r\nIn our EZ Pruning Guide, this variety is in the GREEN pruning category. These Clematis bloom on new vines that emerge from the ground each year. Prune hard in the spring and as often as you like to encourage reblooming and keep the plant as tidy as you like.', 206500, 34, 0x6173736574732f696d672f626573742d73656c6c6572332e77656270),
(9, 'Belle Toulousaine Itoh Peony', 'PEONIES', 'Bring timeless beauty and lasting charm to your garden with the Belle Toulousaine Itoh Peony. This exceptional perennial combines nostalgia with resilience, making it a perfect addition to any garden setting.  With its impressive blooms, robust growth, and enduring beauty, it is the ideal choice for gardeners seeking elegance and reliability. Plant it today and enjoy a garden that delights the senses and stands the test of time.\r\n\r\n \r\n\r\nLarge, Stunning Blooms: Belle Toulousaine Itoh Peony boasts magnificent 8-inch fully double flowers that captivate with their sheer size and beauty. The lush, layered petals create a breathtaking display, adding a touch of elegance to any garden. These impressive blooms are not only visually stunning but also have a delightful fragrance, making your garden a sensory delight.\r\n\r\nStrong and Upright Growth: A standout benefit of the Belle Toulousaine Itoh Peony is its strong stems, which hold the large blooms upright even in adverse weather conditions. This robust growth ensures that your garden remains neat and attractive, without the need for staking. Enjoy a tidy, well-kept garden effortlessly with this resilient peony.\r\n\r\nA Nostalgic, Long-Lived Perennial: This Itoh Peony is more than just a pretty face. It’s a long-lived perennial that will grace your garden for years to come. Plant it in a sunny, well-drained spot and watch it thrive with minimal maintenance. Its enduring beauty and reliability make it a cherished addition to any landscape, bringing joy season after season.', 276500, 30, 0x6173736574732f696d672f37383133382e77656270),
(10, 'La Donna Peony', 'PEONIES', 'Introduce luxury and timeless charm to your garden with the La Donna Peony. This exquisite plant is known for its large, fully double flowers that feature a delightful collage of pink petals and vibrant yellow staminode’s, creating a visual masterpiece that will captivate any onlooker.\r\n\r\n \r\n\r\nStunning Double Blooms: The La Donna Peony showcases magnificent, fully double flowers that are a feast for the eyes. Each bloom is a blend of soft pink petals layered with bright yellow staminode’s, offering a striking and unique appearance.  The La Donna Peony is not only a garden gem but also an excellent choice for cut flowers. Its long-lasting, fragrant blooms are perfect for creating elegant floral arrangements that bring a touch of garden luxury indoors.\r\n\r\nStrong, Resilient Stems: Unlike some varieties, the La Donna Peony is equipped with robust stems that support its large flowers, keeping them upright and elegant. This makes it perfect for adding vertical interest and drama to your garden without the need for staking.\r\n\r\nLong-Lived Perennial: Investing in the La Donna Peony means enjoying its beauty for many years to come. This hardy perennial can endure in your garden for decades, providing stunning blooms every spring with minimal maintenance.  It thrives in well-drained soil and enjoys full to partial sun, making it a low-maintenance addition to any garden.', 66500, 23, 0x6173736574732f696d672f36343331352e77656270),
(11, 'Magical Mystery Peony', 'PEONIES', 'As these incredibly showy, large blooms mature, the astounding, creamy–pink color turns to creamy–white with a lavender picotee edge. They are fragrant, and make stunning cut flowers. Magical Mystery Tour is beautiful in a large pot, but like all Itohs, it is also an extraordinary garden performer with long–lasting, lush foliage. Once mature, it\'s also impressively floriferous. Because of its tree peony ancestry, the stems become woody and strong, holding the blooms up nicely without staking. Itoh peonies are a little harder to find than herbaceous and tree peonies. However, we\'ve worked hard to increase our stock with plenty of especially stunning varieties like Magical Mystery Tour to choose from. Paeonia X itoh \'Magical Mystery Tour\'\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 171500, 32, 0x6173736574732f696d672f3735343737412e77656270),
(12, 'Cora Louise Itoh Peony', 'PEONIES', 'The flowers are huge, up to 10\" across, and the deeper coloring towards the core makes them even more dramatic. They produce a subtle perfume, which is nice for flower arranging. The plant is lush and green, a beautiful backdrop throughout the season. Like all Itohs, Cora Louise is a cross between herbaceous and tree peonies, with top marks in vigor and strength. Once mature, it\'ll produce up to 50 blooms in a season. Great in large containers, or left in a border where it will enhance your garden for decades to come. It\'s easy to grow and tends not to be bothered by deer. Paeonia x \'Cora Louise\'', 206500, 21, 0x6173736574732f696d672f37353533342e77656270),
(13, 'Morning Lilac Itoh Peony', 'PEONIES', 'Delight in single to semi double, vivid fuchsia-purple blooms early in the peony season. Striking blooms cover the tops and sides of this compact plant. A cross between herbaceous and tree peonies, Itoh peonies have a dense, rounded form, a great abundance of 7-9\" flowers and a bloom season that lasts up to six weeks. Grows 25-30\" tall with a 36\" spread. Deer tend to avoid. Paeonia Itoh \'Morning Lilac\'\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 171500, 12, 0x6173736574732f696d672f3637313839412e77656270),
(14, 'Fantastic Peony Collection', 'PEONIES', 'If you\'re not in the mood for classics, why not branch out to score double takes with your peony garden? These lacy flower forms are strikingly ornate over lush green foliage. The flowers are long-lasting in cut floral bouquets, and the foliage stays attractive even after the bloom season is through. The Fantastic Frills Peony Collection will make your green thumb look impressive, but it\'s actually very easy to care for. It will remain beautiful through decades—truly a generational plant. Put it in borders and watch spring butterflies dance over the blooms. All three varieties are delightfully fragrant. Paeonia lactiflora \'Coral Charm\', \'Felix Crousse\', \'Sarah Bernhardt\'.\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 66500, 14, 0x6173736574732f696d672f3635353836415f30326238626330342d333562342d346235342d386531302d6464386134613061353763362e77656270),
(15, 'Sarah Bernhardt Peony', 'PEONIES', 'Gorgeous peonies are sweetly scented and grace your landscape with some of the biggest, most colorful spring blooms you\'ll find! Fancy double blossoms reach up to 5-6\" across! Paeonia lactiflora \'Sarah Bernhardt\'\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 136500, 17, 0x6173736574732f696d672f3032363833412e77656270),
(16, 'Bouquet Peony Collection', 'PEONIES', 'Our Bouquet Builders Collection takes the guesswork out of creating stunning mixtures of cut flowers. This trio of high-performing, beautifully fragrant peonies complement one another in the garden and in the home. A nice mix of fully double, fragrant peonies in shades of pink, red and white, these three peonies all have strong stems for good flower support. Perfect for creating a hedge or border. Paeonia lactiflora ‘Duchesse de Nemours’, ‘Red Charm’, and ‘Daydream’ have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 206500, 17, 0x6173736574732f696d672f39333931352e77656270),
(17, 'Red Charm Peony', 'PEONIES', 'Splash your garden with bold, showy red flowers in the late spring. The deep red, double flowers stand out in the garden and fresh floral displays. The fine, dark green leaves remain attractive into fall. This long-lived peony produces lots of flowers during its bloom time. It\'s a top choice for foundation plantings, creating a small hedge, planting along a walkway or for mixed perennial flower beds.Paeonia \'Red Charm\'\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 66500, 24, 0x6173736574732f696d672f36323831392e77656270),
(18, 'Sorbet Peony', 'PEONIES', 'The unusual pink and white, 5-7\" double blooms of this hybrid are as delectable as an elegant dessert. Fragrant flowers provide breathtaking beauty in early summer, and handsome foliage turns red in fall. Bushy plants grow up to 3\' tall and require no special care. Deer tend to avoid. Paeonia \'Sorbet\'\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 66500, 34, 0x6173736574732f696d672f3830343032412e77656270),
(19, 'Duchesse Lorraine Peony ', 'PEONIES', 'Strong stems support large, creamy white, double blooms with frothy petals, creating quite a showpiece in mid to late spring. Glossy, deep green foliage is attractive and ornamental throughout the growing season. New growth emerges burgundy in spring and turns a soft yellow in fall. Growing 24-30\" tall with a 24-36\" spread, this garden classic is ideal as a small hedge, clustered with other peonies or as a specimen plant. Plant in full sun to partial shade. Deer resistant. 2-3 eye bareroot. Zones 3-8. Paeonia \'Duchess de Nemours\'\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 276500, 22, 0x6173736574732f696d672f36303733355f312e77656270),
(20, 'Bartzella Itoh Peony', 'PEONIES', 'Strong stems support large, creamy white, double blooms with frothy petals, creating quite a showpiece in mid to late spring. Glossy, deep green foliage is attractive and ornamental throughout the growing season. New growth emerges burgundy in spring and turns a soft yellow in fall. Growing 24-30\" tall with a 24-36\" spread, this garden classic is ideal as a small hedge, clustered with other peonies or as a specimen plant. Plant in full sun to partial shade. Deer resistant. 2-3 eye bareroot. Zones 3-8. Paeonia \'Duchess de Nemours\'\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom—but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 171500, 33, 0x6173736574732f696d672f3035303236412e77656270),
(21, 'Canary Brilliants Itoh Peony', 'PEONIES', 'As bright and cheerful as a songbird, Canary Brilliants is an award-winning Itoh that richly deserves the love it receives from gardeners. Lightly scented yellow, semi-double or double flowers are light beige in the bud, then swirl open in mid to late spring. Some blooms remain light yellow, while others become a brilliant yellow with apricot hues in the center. This peony is an exceptional example of an Itoh--Canary Brilliants offers the longevity and hardiness of a bush peony, with the lovely coloring of a tree variety. Canary Brilliants has long, sturdy stems that grow to nearly 30 inches tall. This peony can produce 30-50 blooms per season once established, and doesn\'t clutter the garden with pollen or seeds. Paeonia x \'Canary Brilliants®\'', 171500, 16, 0x6173736574732f696d672f38373736332e77656270),
(22, 'Caroline Constabel Peony', 'PEONIES', 'Caroline Constabel Itoh Peony, a new and high-performing variety, produces lightly scented, fully double, dusty-pink flowers, ringing a center ring of yellow stamen against a dark-colored core. This stunning mauve peony will produce three to five gorgeous blooms per stem, thanks to it relation to beautiful, heavily-flowering tree peonies. Thanks to its heritage on the herbaceous side, Caroline Constabel is also outstandingly cold hardy, with deep green foliage that holds its color from spring to fall. Strong stems hold up to any weather and are wonderful for cutting. This feminine, strong peony is sure to please in the vase and in the garden. Paeonia Itoh \'Caroline Constabel\'', 276500, 26, 0x6173736574732f696d672f39323733312e77656270),
(23, 'Duchess de Nemours Peony', 'PEONIES', 'The Itoh is the dream peony—a coveted hybrid from herbaceous and tree peonies that\'s much harder to obtain. We\'ve been building up our selection of these extraordinary hybrids, and Duchesse de Lorraine is a particularly exciting find. This is a breakthrough Itoh—It has the most petals of any other yellow peony. Nearly twice the petals of the famous cultivar Bartzella. They appear on strong stems, and produce a delightful fragrance. Once Duchesse de Lorraine matures, it\'ll provide tons of blooms for both the garden and cut flower displays. The foliage will remain a lush green backdrop for your perennial garden bed through the season, and the plant itself will last decades in the right spot. It is excellent in containers, borders and mass plantings. The blooms attract butterflies and are deer resistant. This très jolie variety is named for the Lorraine region in France. Paeonia x \'Duchesse de Lorraine\' PP26907\r\n\r\nPeonies have few requirements: give them a sunny well-drained location, plant 2-4\' apart, with the eyes (new buds at the crown) no more than 2\" below soil level and apply fertilizer or compost in spring. They take a while to establish, often 3 years before the first bloom--but the wait is worth it. They are heirloom quality. Let them grow undisturbed and they will bring joy to you and your loved ones through the decades.', 171500, 4, 0x6173736574732f696d672f3233383231412e77656270),
(24, 'Glowing Embers Hydrangea', 'HYDRANGEAS', 'A compact hydrangea that produces vibrant red to dark pink summertime blooms. Growing 3-5\' tall, it has lush foliage that makes it attractive throughout the season. Its dried flower heads looking stunning in floral arrangements. Plant in full sun to partial shade. Zones 5-9. Hydrangea macrophylla \'Glowing Embers\'', 101500, 22, 0x6173736574732f696d672f3830333838412e77656270),
(25, 'Forever Pink Hydrangea', 'HYDRANGEAS', 'This mophead hydrangea is aptly named—it\'ll hold its color beautifully throughout the flowering season. It\'s a great variety for the garden, there\'s no big insect or disease dramas. It\'ll also bring in the beneficial pollinators. You can also bring the blooms out of the garden. A few flower heads create a beautiful fresh-cut or dried flower arrangement. If you want that vibrant pink color, alkaline soil is best. Add lime to soil if necessary. Hydrangea macrophylla \'Forever Pink\'', 136500, 12, 0x6173736574732f696d672f3733343238412e77656270),
(26, 'Hydrangea Magical Allure', 'HYDRANGEAS', 'Boasting an alluring, near picotee pattern, Magical Allure Hydrangea\'s flower heads burst into a multitude of sugared pink tones, and holds that color well throughout the bloom season. Each petal appears frosted due to the saturation of color at the edges. The bright pinks contrast beautifully against the deep, coppery foliage that makes Allure an excellent specimen or hedge plant.\r\nThis hydrangea blooms on only old wood, so pruning should be done selectively to ensure that you\'ll enjoy a color display each year. After flowering in summer, lightly prune your stems back to the healthy buds, and remove weak or damaged stems in springtime. Hydrangea macrophylla \'Hokomalure\' PPAF', 136500, 34, 0x6173736574732f696d672f39333532342e77656270),
(27, 'Annabelle Hydrangea Shrub', 'HYDRANGEAS', 'Expect for this plant to have clusters of small white blooms that appear in midsummer and gently fade to a wonderful shade of green. Annabelle Hydrangea shrubs bloom without fail each season to create a bold statement for the landscape. It\'s great for dried arrangements, too! Expect for Annabelle Hydrangea shrubs to be adaptable, surviving soil of all different kinds of pHs, and durable, with blooms lasting all through summer and sometimes through fall and winter. These blossoms can also grow up to be a foot across, making them a great statement piece for your garden. Annabelle Hydrangea shrubs need to be pruned once a year to remain healthy, so make sure to trim them back so their beautiful blossoms can return time and time again. Hydrangea arborescens \'Annabelle\'', 84000, 22, 0x6173736574732f696d672f3639313936412e6a666966),
(28, 'Tellers Blue Hydrangea', 'HYDRANGEAS', 'Blue is a rare and coveted color in gardens. In more acidic soil, Tellers Blue will give you some of the best brilliant blue color to set apart your garden design. Planted as a shrub border, this will provide lush foliage through multiple seasons and darling lacecap flowerheads through summer. They\'ll attract birds and beneficial pollinators to the garden. You can also create an eye-catching feature with Tellers as a patio accent, or snip some blooms for an indoor arrangement. Hydrangea macrophylla \'Blaumeise\'', 84000, 23, 0x6173736574732f696d672f3733343330412e77656270),
(29, 'Riven Lace Hydrangea', 'HYDRANGEAS', 'Neatly split green buds open into filigree blooms on this smooth-leaf plant. Serrated leaves reminiscent of a Japanese Maple. 4\" pot. Hydrangea arborescens \'Riven Lace\'', 101500, 12, 0x6173736574732f696d672f38373534302e6a666966),
(30, 'Pink Diamond Hydrangea', 'HYDRANGEAS', 'An excellent shrub for the back border, a foundation planting or the landscape, its long, 8-12\" pink panicles bloom from summer into fall and they create a colorful show in the garden or in floral arrangements. Hydrangea paniculata \'Pink Diamond\'', 84000, 30, 0x6173736574732f696d672f3831353336412e77656270),
(31, 'Endless Summer Hydrangea', 'HYDRANGEAS', 'There are plenty of red hydrangeas in Europe, but USA doesn\'t really have the climate for this color in hydrangeas. It didn\'t come close, until Summer Crush, whose rich raspberry red hues are the nearest to true red that any hydrangea has ever been in US soil. It\'s on a gorgeous, impressively heat–tolerant plant, too. Rich green, serrated foliage fills out a compact habit, up to 3\' tall. It is extremely bud hardy, so it will reliably bloom on both old and new wood. The wealth of flowers will bring on the butterflies. Also, as a macrophylla, it changes colors depending on the pH balance of the soil, but not to the typical blue. If your soil is more acidic, with a good aluminum availability, it will flower in rich purple. Hydrangea macrophylla \'Bailmacfive\' PP30359', 311500, 40, 0x6173736574732f696d672f3833333535412e77656270),
(32, 'Hydrangea Forever Together', 'HYDRANGEAS', 'Plant this compact hydrangea into a border along a low fence or edging a sidewalk, and it\'ll reward you with large double mophead blooms that change colors as they mature. They will start out light green in spring, and by late summer they will mature to violet or pink. Be sure to check your soil\'s pH level if you\'re looking for a specific bloom color. About 5.2-5.5 produces violet flowers, about 6.0-6.2 produces pink flowers. This dwarf shrub also draws attention as a container accent, and attracts butterflies. Be sure to check your soil\'s pH level if you\'re looking for a specific bloom color. About 5.2-5.5 produces blue flowers, about 6.0-6.2 produces pink flowers. Hydrangea macrophylla \'REI05\'', 451500, 28, 0x6173736574732f696d672f39333532362e77656270),
(33, 'First Edition Hydrangea', 'HYDRANGEAS', 'First Editions® Vanilla Strawberry™ Hydrangea blooms in sweet, creamy white with a flavorful splash of pinks and red later in the season. Huge, high-piled panicles of white blooms emerge in midsummer to be held upright on strong, red stems. The flowers transition to pink as nighttime temperatures cool, finally turning to a strawberry red in the late season. As new blooms pop up on these panicles, you\'ll enjoy a mix of cream and berry-red flowers on each stem. By late season, these upright plants will show off a cascade of flower heads reminiscent of strawberry-and-vanilla-swirled ice cream cones. Hardy in nearly all of the United States, Vanilla Strawberry™ Hydrangea produces enough blooms to fill your garden, your cut arrangements, and your dried displays. Butterflies and other pollinators will help themselves to these treat-like flowers, too. Hydrangea Paniculata Vanilla Strawberry™ 20670', 3500, 34, 0x6173736574732f696d672f38373433352e77656270),
(34, 'Limelight Hydrangea', 'HYDRANGEAS', 'Vigorous and upright, limelight hydrangea are known for their impressive rounded-form shrub that is covered in large clusters of creamy white florets that mature to chartreuse green in the midsummer weeks. As fall approaches, the dense flower panicles of these hydrangea bushes change to deep pink for an altogether different look. Limelight hydrangea bushes have sturdy stems that keep the flower heads upright and visible through any kind of weather. Robust plants can reach a height of 13 feet and will be loaded with 8-12\" flowers in no time. The limelight hydrangea shrub is a perfect choice for mass planting, mixed shrub border, or as an anchor in a woodland garden. Does best in moist, but well-drained soil. Blooms on new wood--prune in late fall to early spring for increased flowering. Hydrangea paniculata \'Limelight\' PP12874', 84000, 19, 0x6173736574732f696d672f3935303035412e77656270),
(35, 'Snowcicle Oakleaf Hydrangea', 'HYDRANGEAS', 'Oakleaf Hydrangea shrubs, such as this unique Snowcicle Hydrangea, make quite a scene in the landscape. Whether a single shrub or a group, the snowcicle oakleaf hydrangea makes a wonderful flower-filled display with its thick clusters of white florets from large panicles that cover the 4-6\' shrub all summer long. The florets on this oakleaf hydrangea age from their white to soft rose-red, then change to a light green hue as the season goes on. At times, your landscape will be awash in all three colors at once. Works well as a specimen planting to anchor a flower bed or cutting garden. Plant three or more of these snowcicle oakleaf bushes as a hedge or screen to create small, private areas perfect for al fresco dining or simply enjoying the view. Dry flower heads for interesting indoor arrangements. Hydrangea quercifolia \'Snowcicle\' PP33072', 3500, 34, 0x6173736574732f696d672f3732383631412e77656270),
(37, 'Firepot Dahila', 'FLOWER BULBS', 'The Firepot Dahlia is a showstopper with its fiery hues and perfectly compact form.  It is deal for both large gardens and containers. Its bold waterlily-like blooms in beautiful shades of sunset coral pink and yellow, make it the perfect centerpiece for any outdoor space. Standing at 2-3 feet tall, this dahlia offers a big impact in a small package. Whether you\'re looking to brighten up a garden bed, patio, or create stunning cut-flower arrangements, the Firepot Dahlia is the perfect choice. \r\n\r\nBright and Beautiful Blooms for Every Occasion: Firepot Dahlias are perfect for creating eye-catching displays in garden beds or planters. Their compact size allows them to work beautifully in containers, making them versatile enough for small gardens, patios, and balconies. They bloom from midsummer until the first frost, offering a long-lasting display of color in the garden.\r\n\r\nEasy to Grow, Hard to Miss: At just 2-3 feet tall, these dahlias are easy to care for while still offering maximum visual appeal. Plant several of them and they will become the focus of your summer garden. Dahlias are relatively low maintenance, requiring full sun and well-draining soil to thrive. With regular deadheading, you\'ll enjoy continuous blooms throughout the season. \r\n\r\nBeautiful in Cut Flower Arrangements: This dahlia features large, water lily-like, bi-colored petals that typically transition from rich pink or reddish hues at the edges to bright yellow near the center, creating a fiery, sunset-like effect. The show-stopping blooms are excellent for fresh bouquets, giving your home a burst of color with every cut.', 10500, 44, 0x6173736574732f696d672f39333839342e77656270),
(38, 'Missis Dutch Dahila', 'FLOWER BULBS', 'With its distinctive incurved petals and striking two-tone coloring, the Missis Dutch Dahlia is a true standout in any garden. This dahlia offers a dramatic display, featuring blooms with a lovely contrast between their bright pink outer petals and lighter undersides. Not only does it add a unique visual texture to garden beds, but it also makes an exceptional cut flower, perfect for fresh bouquets. Compact and versatile, Missis Dutch performs beautifully in containers and garden beds alike. \r\n\r\nA Unique Addition to Your Garden or Patio: Missis Dutch’s intricate incurved petals create a beautiful and unique floral shape. The bloom is so unique that some put it into the Cactus bloom class and others put it in the Novelty class.  Either way, the contrasting colors on each petal—vibrant pink with a soft reverse—make it a real eye-catcher. Whether planted in garden beds or in containers, this dahlia’s size and bold blooms will make a statement all season long.\r\n\r\nPerfect for Containers and Bouquets: If you love creating your own floral arrangements, Missis Dutch Dahlias are the perfect choice. Their long-lasting, bold blooms add a splash of color to any bouquet, and the cactus-style shape adds texture and interest. With its compact growth habit, this variety thrives in containers, making it ideal for smaller spaces like patios and decks.\r\n\r\nLow-Maintenance Beauty: Like all dahlias, Missis Dutch is relatively easy to grow. It thrives in full sun and well-draining soil, and with regular deadheading, you’ll enjoy continuous blooms from summer through fall. These dahlias are also perfect for attracting pollinators, bringing life and movement to your outdoor space.', 10500, 40, 0x6173736574732f696d672f39333839362e77656270),
(39, 'Pooh Dahlia ', 'FLOWER BULBS', 'The Pooh Dahlia is a true standout, with its vivid orange and yellow blooms creating a burst of sunshine in your garden. Known for its open-face collarette bloom, this dahlia invites pollinators like bees and butterflies, making it a perfect choice for eco-conscious gardeners. With an abundance of flowers throughout the season, you’ll enjoy both vibrant color and environmental benefits, all while bringing pollinators to your outdoor space. \r\n\r\nA Pollinator’s Dream: The open-face design of the Pooh  Dahlia is a natural invitation for pollinators. Its bright orange and yellow petals, combined with an accessible center, attract bees and butterflies all season long, adding lively movement and energy to your garden. \r\n\r\nPerfect for Bouquets: Looking to bring your garden’s beauty indoors? The Pooh Dahlia’s sturdy stems and floriferous nature make it ideal for cut flowers. Create cheerful, long-lasting arrangements that brighten any room with ease. The blooms hold up beautifully in vases, offering a steady supply of fresh floral displays.\r\n\r\nLow-Maintenance Color All Season: With its high bloom rate and long-lasting flowers, the Pooh Dahlia delivers continuous beauty with minimal effort. Plant it in sunny spots and watch as it thrives from mid-summer through fall, offering color and vibrancy when many other plants are starting to fade.', 10500, 33, 0x6173736574732f696d672f39353232362e77656270),
(40, 'Double Jill Dahlia ', 'FLOWER BULBS', 'The Double Jill Dahlia offers a mesmerizing mix of pink, white, yellow, and orange petals that create a stunning visual display in your garden. With its large blooms and tall, robust plants, this decorative dahlia is perfect for filling your flower beds or becoming a statement piece in your landscape. Not only is it floriferous, but it also provides long-lasting color, producing abundant flowers all season long.  \r\n\r\nMulti-Colored Delight: The unique color palette of the Double Jill Dahlia brings a beautiful blend of soft pinks, warm oranges, sunny yellows, and bright whites, all combined in one bloom. These vibrant flowers can effortlessly elevate your garden’s aesthetic, creating a cheerful and inviting space for you to enjoy.\r\n\r\nExcellent Cut Flowers: With its tall, sturdy stems and abundant blooms, the formal decorative flower of Double Jill Dahlia is an excellent choice for fresh-cut flowers. Add a pop of multi-colored elegance to your home by creating stunning arrangements with these long-lasting, decorative blooms. \r\n\r\nHigh-Impact Garden Presence: Standing tall with large, showy flowers, the Double Jill Dahlia makes a significant impact in any garden. Whether planted in borders, flower beds, or large containers, these dahlias will command attention, offering a season-long display of vibrant color and beauty.', 10500, 35, 0x6173736574732f696d672f39353232372e77656270),
(41, 'Fubuki Sakura Dahlia ', 'FLOWER BULBS', 'The Fubuki Sakura Dahlia offers a unique blend of white, pink, and yellow tones with serrated, frilly edges that bring eye-catching texture to your garden. This cactus-style, laciniated bloom stands out with its spiky, layered petals, providing a bold yet elegant presence. Whether planted in a garden bed or used for cut flowers, the Fubuki Sakura Dahlia offers long-lasting blooms, ensuring you’ll enjoy its beauty throughout the growing season.  \r\n\r\nStriking, Frilly Petals: The serrated edges of the Fubuki Sakura Dahlia\'s petals create an intricate, frilly texture that adds depth and dimension to any garden. The petals transition from white to soft pinks, with hints of yellow near the center, creating a stunning multi-colored display that draws attention from every angle.\r\n\r\nLong Blooming Season: Enjoy vibrant color from mid-summer through fall with the Fubuki Sakura Dahlia’s extended bloom time. This dahlia continues to produce its distinctive flowers for months, offering ongoing visual interest when other plants start to fade. \r\n\r\nPerfect for Cutting: The sturdy stems and vibrant blooms of the Fubuki Sakura Dahlia make it an ideal choice for cut flowers. Bring its dramatic, spiky petals indoors to create fresh arrangements that brighten up any room. The long vase life ensures you’ll enjoy its beauty both inside and out.', 10500, 28, 0x6173736574732f696d672f39353232385f65373163386666372d366161632d343465652d613831392d3166363063306334373036372e77656270),
(42, 'Missis Amy Dahlia ', 'FLOWER BULBS', 'The Missis Amy Dahlia will be a garden favorite that offers a spectacular display of vibrant pink blooms with a unique pincushion center, surrounded by delicate recurved petals. Its eye-catching anemone bloom form is not only breathtaking in the garden but also ideal for fresh floral arrangements. With its long stems and floriferous nature, this dahlia will provide you with endless bouquets throughout the growing season. \r\n\r\nA Garden Showstopper: The Missis Amy Dahlia features an exquisite bloom class known as anemone, with a pincushion-like center framed by soft, recurved petals. This unique structure gives each bloom a textured and layered look that stands out in any garden setting. These dahlias thrive in sunny spots and perform well in a range of garden types, from borders to cutting gardens.\r\n\r\nLong-Lasting Blooms: In addition to its striking beauty, the Missis Amy Dahlia is a floriferous variety, meaning it produces an abundance of flowers throughout the growing season. This extended bloom period ensures that you can enjoy vibrant color in your garden for months on end.\r\n\r\nPerfect for Floral Arrangements: Thanks to its long, sturdy stems, Missis Amy is ideal for cutting. Create elegant bouquets with ease, knowing that the flowers will last beautifully in a vase.', 10500, 50, 0x6173736574732f696d672f39353232392e77656270),
(43, 'Seattle Dahlia ', 'FLOWER BULBS', 'The Seattle Dahlia is a bold and vibrant choice for any garden, with its striking 6-8 inch flowers in bright sunshine yellow, accented by white tips. This decorative class dahlia stands out in any landscape with its large, eye-catching blooms. Not only does it offer stunning beauty, but it’s also perfect for creating show-stopping floral arrangements. \r\n\r\nBold and Beautiful Blooms: The Seattle Dahlia delivers a showy display with its bright yellow blooms highlighted by striking white-tipped petals. These oversized flowers, can reach 6 to 8 inches in diameter, and instantly brighten up any garden, making them a stunning focal point. Whether you\'re looking to create a cheerful garden bed or add a warmth of sunshine to your cutting garden, the Seattle Dahlia is a fantastic option. \r\n\r\nExceptional Size and Impact: This dahlia’s large, decorative-class blooms add drama and beauty to your outdoor space. The pristine color combination creates a glowing, cheerful look that can be appreciated from a distance. The Seattle Dahlia stands tall and proud, making it perfect for borders, flower beds, or as an eye-catching feature in containers.\r\n\r\nPerfect for Bouquets: Not only is the Seattle Dahlia ideal for brightening your garden, but its strong, tall stems make it a superb flower for cutting. Add these stunning blooms to any floral arrangement and bring a ray of sunshine inside where their striking colors will bring life and joy to any room.', 10500, 45, 0x6173736574732f696d672f39353233302e77656270),
(44, 'Statue Of Orange Dahlia ', 'FLOWER BULBS', 'The Statue of Orange Dahlia is more than just a flower—it’s a striking statement for any garden. This decorative dahlia features apricot-orange blooms that radiate from a bold, dark center, making it the perfect centerpiece in your garden beds or containers. Complemented by lush burgundy and green foliage, this dahlia offers season-long beauty and contrast that will leave your outdoor spaces glowing with color and texture. \r\n\r\nA Rich Centerpiece: With its large, decorative blooms, the Statue of Orange Dahlia instantly becomes the focal point of your landscape. The apricot-orange petals with a rich, dark center add depth and drama, making it ideal for borders, flower beds, or mixed containers.\r\n\r\nLong-Lasting Color and Visual Interest: This dahlia isn’t just for show—its unique foliage, a blend of burgundy and green, provides additional interest throughout the growing season. It holds up beautifully through the summer, offering you continuous enjoyment well into fall.\r\n\r\nPerfect for Cut Flowers and Arrangements: Not only does the Statue of Orange Dahlia thrive in the garden, but it also makes for incredible cut flowers. Its strong stems and long-lasting blooms allow you to enjoy vibrant, fresh arrangements indoors, bringing the same warmth to your home as to your garden.', 10500, 34, 0x6173736574732f696d672f39343838305f65313638343634352d663232622d343163622d383961642d3365356132636631363166632e77656270),
(45, 'Sunny Boy Dahlia ', 'FLOWER BULBS', 'The Sunny Boy Dahlia brings warmth and cheer to any garden with its radiant golden-yellow blooms, each petal beautifully tipped with a soft red hue. This ball dahlia is known for its perfectly rounded, fluted petals, giving each flower a full and lush appearance. Standing tall and proud, Sunny Boy is not only an excellent garden showpiece but also a premium cut flower, ideal for vibrant floral arrangements. Its cheerful, long-lasting blooms will brighten any outdoor space or home throughout the summer and fall. \r\n\r\nA Burst of Sunshine in Every Garden: The Sunny Boy Dahlia’s bright yellow petals, delicately tipped with red, create a stunning contrast that draws attention in any garden setting. The fluted petals give the blooms a soft yet structured look, adding both texture and depth to garden beds and containers alike.\r\n\r\nPerfect for Cut Flower Bouquets:  As a ball type dahlia, which is uniform in height and shape, Sunny Boy makes a premium cut flower.  It is a perfect choice for anyone who loves to bring fresh, brightly colored flowers indoors. Its sturdy stems and long-lasting blooms make it a great addition to a cheerful, sunny bouquet.\r\n\r\nLow Maintenance and High Impact: Sunny Boy Dahlias are easy to care for, thriving in full sun and well-draining soil. With regular deadheading, they’ll keep producing blooms all season long, from summer into early fall. Whether you\'re a beginner or a seasoned gardener, these dahlias are a reliable way to add bold, beautiful color to your garden.', 10500, 78, 0x6173736574732f696d672f39333839372e77656270),
(46, 'Tiny Massive Asiatic Lily', 'FLOWER BULBS', 'Whoa!  These eye-catching black and yellow flowers of the Tiny Massive Asiatic Lily combine striking color with a high bud count.  This grants you an impressive show in a surprisingly compact form. These lilies bring sophistication and energy to gardens, pots and small spaces alike.\r\n\r\nBrilliant Color Contrast with High Bud Count\r\nWith a high bud count of bold, two-tone black and yellow blooms, this lily will quickly earn star status in any garden, from container displays to borders. Its compact size allows it to shine even in small spaces, giving your garden a modern, chic appeal.\r\n\r\nLow Maintenance and High Reward\r\nAsiatic lilies are among the easiest lilies to grow and care for, and you’ll enjoy long-lasting, high-impact displays with minimal effort. They’re also weather-tolerant and perform well in many climates, so you don’t have to worry about fussing over their needs year after year.\r\n\r\nPerfect for Containers and Garden Borders\r\nThe compactness of this variety makes it a wonderful choice for adding height and drama to containers, patios or balconies. In garden beds, it creates beautiful, layered looks without overwhelming nearby plants.', 10500, 36, 0x6173736574732f696d672f39343931332e77656270),
(47, 'Labyrinth Dahlia', 'FLOWER BULBS', 'The name alone evokes mystery and romance, and Labyrinth doesn\'t disappoint. Whether enjoyed in the garden, or cut and brought indoors for arrangements, the sensory pleasure of these 8-10\" tropical colored, other-worldly flowers cannot be overstated. While dahlias may look difficult to grow, they\'re remarkably easy—they need staking in windy places only if perfectly straight stems are desired. Lifting in fall may also be optional in temperate climates such as our Zone 6b. We mulch heavily and let them be and are rarely disappointed. Planted in masses, Dahlias will fill gaps that develop in the perennial border and make excellent potted plants (1 tuber in a 12\" pot). They prefer full sun, though partial shade will work in the South, and they like rich soil and even moisture. With few pests or diseases to trouble them, these dahlias will keep blooming when other annuals and perennials peter out. They\'re long lived in arrangements too, lasting 7-10 days without fail. Easy-to-grow dahlias are not bothered by deer, rabbits or other garden pests, though bees and butterflies love them. Dahlia decorative \'Labyrinth\'', 10500, 36, 0x6173736574732f696d672f37323531332e77656270),
(48, 'Who Dun It Dahlia ', 'FLOWER BULBS', 'It\'s no mystery why dahlia lovers are swooning over this dinnerplate dahlia. Who Dun It Dinnerplate Dahlia surprises and delights with huge flowers in shades of blue shifting to purple, with white at the center of each petal. This decorative dahlia opens in a bit haphazardly, with petals poking out at bloom time, almost like a cactus dahlia. In full bloom, each flower stands tall, at 7 or more inches wide. You\'ll love these big and bold flowers, and you\'ll receive plenty of them from this generous plant. Plant with bold cottage garden favorites like lupines and asters for a sweet and informal cutting garden.', 10500, 11, 0x6173736574732f696d672f39333239372e77656270),
(49, 'Clematis Josephine', 'CLEMATIS & VINES', 'A stunning climber with fully double, layered blooms, this clematis captivates with dramatic, long-lasting floral displays. Large, 5” lilac base sepals surround pom-pom centers of soft pink, with flowers evolving in shape and form as they mature. The long life of the blooms helps extend the blooming season from June through August, Josephine Clematis delivers continuous beauty to your garden all summer long.\r\n\r\nGorgeous, Fully Double Blooms\r\n\r\nJosephine Clematis boasts large, fully double flowers with layers of lush sepals that create a captivating, pom-pom-like effect. The blooms feature a blend of pink, lavender, and cream hues—turning trellises, fences, or arbors into floral masterpieces.\r\nExtended Flowering Period\r\n\r\nJosephine Clematis blooms go through a series of transitions as the flower matures, yielding vibrant color from late spring to early fall—and extending the bloom time of your Clematis. Each flower has the ability to last for several weeks, ensuring your outdoor areas stay colorful and inviting well into autumn.\r\nPerfect for Vertical Spaces and Containers\r\n\r\nJosephine Clematis is a climber that thrives in vertical spaces, making it ideal for transforming plain walls, fences, or pergolas into a striking display of double blooms. It’s also well-suited for containers, perfect for patios or balconies where it can add a burst of color and charm.', 3500, 25, 0x6173736574732f696d672f38363635342e77656270),
(50, 'Clematis Taiga', 'CLEMATIS & VINES', 'Introduced at the 2017 Chelsea Flower Show in England, Taiga shocked the gardening world with blooms unlike any seen before on a Clematis vine. These bicolor flowers have unusual sepals that curve upward for a star–shaped bloom that looks almost like a passion flower. Unique from the moment it opens, the flower form continues to change and impress as it matures. Clematis \'Taiga\' PBR\r\n\r\nOur experts have been trialing Taiga for several years now in zone 6 with great success, and we are pleased to report that Taiga is reliably hardy to less than –10°F. It\'s an excellent rebloomer, so if the plant looks tired, trim it and watch it rebound quickly.\r\n\r\nIn our EZ Pruning Guide, this variety is in the GREEN pruning category.  Green prune: Green prune Clematis flower best on new shoots and stems that emerge from the ground each spring. Hard prune in late winter or early spring or anytime you want fresh growth and reblooming. ', 3500, 35, 0x6173736574732f696d672f3733303435412e77656270);
INSERT INTO `flower_product` (`product_id`, `product_name`, `product_category`, `product_desc`, `price`, `stock`, `image`) VALUES
(51, 'Clematis Crystal Fountain', 'CLEMATIS & VINES', 'This enchanting Clematis will delight garden visitors with showy blooms. Crystal Fountain is named for the unusual form of its center, where large sprays of pale lavender and green reach to all its sepals. This medium–sized Clematis is very vigorous, . Clematis \'Evipo038\' CRYSTAL FOUNTAIN PP18223\r\nIn our EZ Pruning Guide, this variety is in the YELLOW pruning category. It blooms best on old vine. Use caution when pruning to retain healthy stems from last season for best flowering.', 3500, 10, 0x6173736574732f696d672f3637333731412e77656270),
(52, 'Clematis Perle d\'Azur', 'CLEMATIS & VINES', 'This beloved, classic vine has abundant, nearly translucent sky-blue sepals with deeply grooved midribs and recurving edges, giving the flower a rounded appearance. Robust and romantic, it grows to 12-15\', covering arches, trellises and pergolas with ease. The flowers are large, up to 4-5\" across, and the light green stamen create a pleasing contrast. Blooming by mid-summer into fall, this classic provides color when much of the spring garden is beginning to fade. The perfect companion Clematis, Perle d\'Azur will thrive when planted with other vines and is an especially effective partner for climbing roses. Clematis \'Perle d\'Azur\'\r\nIn our EZ Pruning Guide, this variety is in the GREEN pruning category. These Clematis bloom on new vines that emerge from the ground each year or stems from near the bottom of older vines. Prune hard in the spring and as often as you like to encourage reblooming and keep the plant as tidy as you like.', 3500, 22, 0x6173736574732f696d672f3738313130412e77656270),
(53, 'Clematis Amaranthine', 'CLEMATIS & VINES', 'This extraordinary Clematis from Dutch breeder Ton Hannink features long–lasting flowers that face upward on their stems to greet the sun. With a medium flower size and unusual varied purple color, guests will have no trouble spotting them trailing romantically along a trellis. The foliage is unusual for a Clematis: brilliant green and dissected, as much a pop of color as the vibrant blooms. Amaranthine is brand new and exclusive to Spring Hill Nurseries. It\'s named after a legendary unfading flower of ethereal beauty—and you\'ll find it lives up to its namesake. Clematis \'UTOP01\' PP32583\r\nIn our EZ Pruning Guide, this variety is in the GREEN pruning category. These Clematis bloom on new vines that emerge from the ground each year or stems from near the bottom of older vines. Prune hard in the spring and as often as you like to encourage reblooming and keep the plant as tidy as you like.', 3500, 77, 0x6173736574732f696d672f3634333234412e77656270),
(55, 'Wisteria Amethyst Falls', 'CLEMATIS & VINES', 'Amethyst Falls Wisteria is a charming and compact deciduous vine, beloved across its native United States for its stunning cascades of fragrant, lavender-blue flowers. Unlike its more vigorous Asian counterparts, Amethyst Falls is a native variety featuring a more restrained growth habit. Since Amethyst Falls won\'t take over the landscape, it is suitable for smaller gardens or confined spaces. Its leaves and flowers are smaller than those of Asian wisteria, but it is not quite a \"dwarf\" variety. Flowering on new wood, this wisteria produces a heavy bloom in late spring and a lighter repeat bloom in summer. With its enchanting blooms and manageable size, Amethyst Falls Wisteria is a popular choice for adding a touch of elegance to arbors, trellises, and pergolas in garden landscapes. Wisteris frutescens \'Amethyst Falls\'', 136500, 55, 0x6173736574732f696d672f39323730382e77656270),
(56, 'Clematis Tie Dye', 'CLEMATIS & VINES', 'The original and only Clematis Tie Dye is a vigorous plant raised in upstate New York. Tie Dye shows plenty of American spirit and soul. A large plant with multitudinous blooms, this Clematis makes a big splash and isn\'t afraid to take up space. The variegated coloring is evocative of your favorite vintage tee shirt.\r\n\r\nSimple flowers make a huge impact in such large numbers, especially with this unique coloration. Tie Dye\'s open, outward-facing form shows off purple and white variegation on each sepal. And, what a performance this Clematis gives in the summer, with non-stop flowers opening one after another. Plant Clematis Tie Dye in a sunny position on a tall pergola or arch, and show off its one-of-a-kind color by pairing with a red rose or a pure white Clematis like Snowstorm. Clematis \'Tie Dye\'\r\n\r\nIn our EZ Pruning Guide, this variety is in the GREEN pruning category. These Clematis bloom on new vines that emerge from the ground each year. Prune hard in the spring and as often as you like to encourage reblooming and keep the plant as tidy as you like.', 3500, 34, 0x6173736574732f696d672f3836303333412e77656270),
(57, 'Grande Diva Jessye Wisteria ', 'CLEMATIS & VINES', 'What brings more character to a home than beautiful, draping, perfumed wisteria? These perennial vines already have the power to command attention and make a garden stand out. But, Grande Diva® Jessye Wisteria, is your key to a garden design like no other. Grande Diva® Jessye is brand new and comes to us from our friends at Pepinieres Minier in France. Spring Hill is one of very few places you\'ll be able to find it on the market in 2021. The bold look of Jessye includes a regal melange of purple, double flowers tightly packed along the racemes. These racemes reach up to 12\" long, hanging down nicely from an arch or pergola. You\'ll really get that draping effect, with precious flowers raining down above your head. Like any wisteria, Jessye grows with strong, woody, curving branches. You can train it up a wall--right around a window you\'d like to open for fragrant breezes, over a strong structure or keep it as a standard in your garden border. Use its bushy habit as privacy by training it along a fence or add curb appeal in a quiet front yard. Wisteria floribunda \'MinwiCB02\'', 416500, 37, 0x6173736574732f696d672f3830363130412e77656270),
(58, 'Pearly Gates Climbing Roses', 'ROSES', 'Spring Hill\'s Pearly Gates climbing roses produce exceptionally large flowers that are a pure pastel pink color you rarely see in these types of rose bushes. Like old-fashioned roses in form with a strong, sweet scent, they open all the way to the ground on sturdy 10-12\' canes! These pink climbing roses bloom on both old and new wood, so you will have lots of flowers throughout summer and fall, and its disease resistance is well above the norm. All this from a rose plant discovered growing in a home garden in Missouri! Rosa \'WEKmeyer\' PP10640', 171500, 32, 0x6173736574732f696d672f3734303431412e77656270),
(59, 'Twilight Grandiflora Rose', 'ROSES', 'Spring Hill\'s Pearly Gates climbing roses produce exceptionally large flowers that are a pure pastel pink color you rarely see in these types of rose bushes. Like old-fashioned roses in form with a strong, sweet scent, they open all the way to the ground on sturdy 10-12\' canes! These pink climbing roses bloom on both old and new wood, so you will have lots of flowers throughout summer and fall, and its disease resistance is well above the norm. All this from a rose plant discovered growing in a home garden in Missouri! Rosa \'WEKmeyer\' PP10640', 136500, 43, 0x6173736574732f696d672f3635353438412e77656270),
(60, 'The Limit Climbing Rose', 'ROSES', 'This hardy, free-flowering yellow climber is sure to become a favorite. Its clusters of fragrant, 4\" buttery yellow flowers cover this climbing rose while it clean, green foliage provides a perfect backdrop for the flowers. This rose is unusually hardy and disease resistant for a yellow rose. Bareroot. Rosa cv. \'WEKprimsoul\' PPAF', 171500, 46, 0x6173736574732f696d672f3632393338412e77656270),
(61, 'Gold Hybrid Tea Rose', 'ROSES', 'It\'s so enjoyable to watch these blooms grow—as they mature, they\'ll turn from orange to gold to amber. The tall, bushy and upright habit is beautiful in the garden, with very clean, disease resistant foliage. You should also grab some for a fresh bouquet, they\'ll light up a room. Rosa cv. \'WEKgobafa\' PPAF', 136500, 65, 0x6173736574732f696d672f3635353431412e77656270),
(62, 'Neil Diamond Hybrid Tea Rose', 'ROSES', 'An eye-catching pattern of broken, bright pink and icy white stripes cover the soft petals of this unusual hybrid tea rose. Like its famous namesake, Neil Diamond is a rock star in the garden or landscape, bearing an abundance of blooms during the long growing season. The flowers are medium-large, growing to 4-5\" across, with a classic tea rose form. Makes a sensational addition to a brightly colored mixed border or bed. Plant in groups along a walkway and take in the strong, heady fragrance as you stroll through the landscape on a warm summer day. Sturdy stems keep blooms upright—perfect for creating fantastic cut-flower displays all season long. Rosa cv. \'WEKdereroro\' PP27272', 241500, 16, 0x6173736574732f696d672f3735313737412e77656270),
(63, 'Frida Kahlo Floribunda Rose', 'ROSES', 'This floribunda rose bush has it all - novel coloring, loads of blooms, and great disease resistance. When we saw Frido Kahlo roses in the test gardens, we loved how the clusters of striped flowers in warm hues of yellow, orange, and red stood out against the dark green, full foliage. Adding to its charm is its slight tea fragrance. A vigorous, upright perennial rose shrub, it has 5-6 flowers per cluster. Rosa cv. \'WEKcifrabaun\' PPAF', 136500, 52, 0x6173736574732f696d672f3632373138412e77656270),
(64, 'New Dawn Climbing Rose', 'ROSES', 'Every morning will feel like the start of something fresh with our New Dawn modern climbing rose. These large, fragrant, ballet-pink flowers will beautifully grace a cottage or country garden, or add romance and vigor to a trellis. New Dawn blooms on new and old wood, making for a manageable, easy-to-train climbing rose. This climber blooms from late spring to frost, and the seasonal show doesn\'t end with the blooms. You\'ll see abundant rose hips in autumn, that you can leave on the vine for winter appeal. In spring, you\'ll love the glossy, dark-green leaves of New Dawn as you wait for this rose to burst into bloom. Rosa \'New Dawn\'', 171500, 51, 0x6173736574732f696d672f3638353332412e77656270),
(65, 'Grace Grandiflora Rose', 'ROSES', 'Many U.S. home gardeners appreciate the English style rose gardens. However, when true English roses are grown here, they tend to be really tall and spiky—not well balanced at all. So the breeder, Christian Bedard worked to create a more compact, even habit that would stick to the English style flower form and style. State of Grace™ is the gorgeous result. Starting with U.S. hybridization meant this new cultivar would adapt better to our climates. It has excellent downy and powdery mildew resistance, and good all-around disease resistance. The habit is uniform, compact and rounded with flowers tidily blooming and reblooming on top. As the name describes, the transition from bud to bloom is seamless here, the flowers staying elegant throughout. The coloring is very elaborate, too. Bronzy pink outer petals stretch to reveal a gorgeous golden center, all hues blending together into a nice, soft tone. As a grandiflora, it\'ll produce 3-4 of these nice large flowers in a cluster. They\'ll be accompanied by a moderate fruit fragrance, and tons of the neighborhood butterflies. Rosa hybrid \'Wekspodotogi\'', 136500, 34, 0x6173736574732f696d672f3630383339412e77656270),
(66, 'Dublin Bay Climbing Rose', 'ROSES', 'Send this giant rose up the latticework of an arbor, let it crawl along a wall or fence, or train it to climb a pillar. Because it grows up to 12\' tall at maturity, you have any number of options. Regardless of how you use this magnificent climber, it\'s sure to add some pizzazz to your landscape. Dublin Bay is highly regarded for its vigorous growth, seemingly ceaseless flower production, brilliant coloring and strong resistance to disease. Its clear, true red, fully double flowers form on new and old wood, covering the plant from spring until frost with huge, 4½\" blooms. Not only will these hardy blooms open in cool weather, but they are tough enough to take the heat. Rosa \'Dublin Bay\'', 241500, 67, 0x6173736574732f696d672f3736363533412e77656270),
(67, 'Promise Grandiflora Rose', 'ROSES', 'Named for the steadfast and beloved Downtown Abbey character, Anna\'s Promise is a vibrant and sweet Grandiflora. Elegant blossoms, with about 35 petals per flower, each open as an artwork of bicolor golden and blush, with a copper reverse. These lovely flowers are set against dramatic, glossy foliage, and carry a sweet and fruity fragrance. Flowers open double or single in small clusters, and you won\'t be able to take your eyes off the elegantly pointed buds that appear throughout a long growing season. A wonderfully hardy Grandiflora, Anna\'s Promise will make a big impression as a stand-alone in your rose garden or as a hedge. Rose cv. \'WEKdoofat\'', 241500, 33, 0x6173736574732f696d672f3835383130412e77656270),
(68, 'Coral Freedom Rose ', 'ROSES', 'An intimate garden space is easier to create than it sounds when you choose Coral Freedom Rose. Reaching heights up to 6\' tall, this carefree cultivar forms a lovely low hedge liberally dotted with vivid coral-peach roses from late spring to fall. Plant Coral Freedom in a line around the perimeter of your garden space and let the plants do the rest. Full, 3½\" flowers open completely and resemble the classic, old-fashioned form of traditional rose types. Makes a fine focal point specimen or border planting, luring plenty of butterflies to the site. Excellent choice for cut-flower arrangements, too. Rosa \'WEKframcace\'', 101500, 71, 0x6173736574732f696d672f3735333831412e77656270),
(69, 'Romeo Dwarf Cherry Tree', 'FRUITS TREES & BUSHES', 'Our dwarf cherry trees for sale at Spring Hill Nurseries will make you fall in love with its handsome, self-pollinating self. This fruit tree produces up to 30 pounds of sweet, deep crimson cherries that have a high flesh-to-pit ratio and doesn\'t split. The cherries are excellent for making juice, canning, baking, and, of course, eating fresh.\r\nThis beautiful Romeo cherry tree produces white-pink flowers in the middle of Spring adding an elegance to your garden just when you need it. It thrives in a full sunlight area with soil that is sandy, organic, and drains well. You\'ll want to prune at the beginning of Spring to ensure your Romeo dwarf cherry tree is beautiful for its blooming flowers. Prunus \'Romeo\'', 241500, 23, 0x6173736574732f696d672f3039343637412e77656270),
(70, 'Mayer Lemon Tree Plan', 'FRUITS TREES & BUSHES', 'The Meyer lemon plant is prized among popular varieties for its slightly sweeter, distinctive flavor. It has a delightful hint of tangerine. Ripening the fruit does not require as much heat as ripening other lemon varieties take. And when a Meyer lemon ripens, the soft skin takes on orange hues. Typically, Meyer lemon trees can grow to be 6 to 10 feet if planted outside. As an indoor potted plant, these trees will reach about 4-6\' tall. Your Meyer lemon plant will need to be moved indoors during the cooler months, but the plant is easy and compact, so it\'s not a problem.\r\nPrior to yielding lemons, the Meyer lemon tree sprouts sweetly-scented white blossoms that will be sure to brighten up any space. The Meyer lemon tree plant usually flowers twice a year and the blooms are fragrant, which is a lovely way to freshen up the home in winter.\r\n\r\nThis self-pollinating delight will make the perfect addition to any space. Citrus limon x \'Meyeri\'', 241500, 23, 0x6173736574732f696d672f4d657965725f4c656d6f6e732e77656270),
(71, 'Carmine Jewel Dwarf Cherry', 'FRUITS TREES & BUSHES', 'Carmine Jewel is a totally new kind of cherry, combining the lusciousness of sweet cherries with the complex flavors of pie or tart cherries and the easy-to-maintain, dwarf-growth habit of bush cherries. You\'ll never need (or want) another cherry! Loads of large, wine-colored fruit cover this 6-ft. bush in August. Cherries have a small pit and are exceptional for fresh eating, pies, preserves, canning, freezing, wine and juice. With yields of 15+ pounds by the fourth year, and 20-30 pounds in its fifth year, you are sure to have enough fruit for all your favorite uses. Not much bothers this tough but beautiful shrub. Carmine Jewel is very easy to grow and maintain. It is extremely cold-hardy and has very little pressure from pests or disease. It can easily double as an ornamental landscape feature with an attractive growth habit, dense, rich green foliage and lovely pink and white blossoms in the spring. As an added bonus, you\'ll never have to worry about suckers of inferior quality popping up—Carmine Jewel is grown on its own roots, not grafted like most cherries. Self-pollinating. Prunus fruticosa x Prunus cerasus', 3500, 44, 0x6173736574732f696d672f3039343636412e77656270),
(72, 'Northland Dwarf Blueberry', 'FRUITS TREES & BUSHES', 'You can grow blueberries even if you\'re up in a chilly northern zone-this is the most cold-hardy blueberry bush yet. It\'s more compact, only growing to about 3-4\', but still bears around 15-20 lbs of berries once it matures. The fruit has a nice bright color and crisp texture, with a delightful wild blueberry taste. The berries a delicious healthy snack and the perfect conversation-starting feature on a hors d\'oeuvres tray. This semi-dwarf bush is also fantastic for landscaping, especially if you\'re looking to create a container focal point. It\'s self-pollinating and just the right size for a large pot, and the bountiful berries look like little gems. Then in fall, the foliage turns a bold yellow-orange hue, with brilliant yellow stems for an extra pop of color in the autumn garden. It\'s a creative way to create a more dynamic garden design. Vaccinium \'Northland\'\r\nProduct Details', 259000, 31, 0x6173736574732f696d672f3736343537412e77656270),
(74, 'Juliet Dwarf Cherry Tree', 'FRUITS TREES & BUSHES', 'Juliet\'s cherries with rich, complex flavor are a favorite for eating fresh, but are delicious when used for baking, jams and ice cream, and freeze beautifully. Growing just 5-to 8- ft. tall, Juliet is a breeze to care for and harvest, yet still yields up to 25-lbs. of fruit. Plants are attractive incorporated into the landscape or planted in large containers. Abundant, white flowers, glossy green foliage and attractive bush habit allow it to double as an ornamental. Self-pollinating.', 3500, 66, 0x6173736574732f696d672f3631363634412e77656270),
(75, 'Grape Thompson Seedless', 'FRUITS TREES & BUSHES', 'The Thompson Seedless Grape stands out as one of the most beloved varieties of white table grapes. A cherished go-to for snacking, these medium-sized fruits boast a delightful, sweet flavor profile without any lingering bitterness. Beyond their exceptional freshness, these grapes prove to be versatile, and ideal for transforming into golden raisins through the drying process. The perfect snack for kids of all ages, sweet white grapes are a healthy treat--and, you\'ll marvel at the difference between fresh grapes and those from the store. When mature, the dependable vines produce up to thirty large, well-filled clusters of grapes. An attractive vine that fits right into the ornamental garden. Vitis vinifera \'Thompson\'', 241500, 34, 0x6173736574732f696d672f39323635342e77656270),
(76, 'Pear Chojuro Std', 'FRUITS TREES & BUSHES', 'Chojuro Asian Pears consistently earns high acclaim from our researchers for its unparalleled richness of flavor. Originating in Japan in 1895, the Chojuro Pear Tree produces visually striking fruits, measuring over 3 inches, characterized by an appealing yellow-brown, russeted exterior and crisp, white flesh. Fragrant white flowers appear in spring before fruiting. Not only attractive but also delicious, these pears deliver a distinctive butterscotch-like flavor.\r\nNoteworthy for its productivity, Chojuro Pear offers an abundant yield, with the fruits maturing in early fall. These pears stay crisp in the fridge for up to five months, so save some for fall and yuletide feasting. To optimize fruit size, judicious thinning of the trees is recommended. Note that you will need another pear tree for pollination. Pyrus communis \'Chojuro\'', 469000, 11, 0x6173736574732f696d672f39333336312e77656270),
(77, 'Goji Berry ', 'FRUITS TREES & BUSHES', 'Claimed to enhance the immune system, improve eyesight and circulation, and protect the liver, Goji Berries are truly a superfood. Small clusters of white-to-lilac funnel-shaped blooms make way for bright orange-red, 1/2\" to 1\" berries in late spring through late fall. The fruit has a slightly sweet, mildly tangy flavor and can be eaten fresh, made into juice, wine or herbal tea, or dried and enjoyed as a snack similar to raisins. Lycium barbarum', 3500, 87, 0x6173736574732f696d672f37383231372e77656270),
(79, 'Hearts Patio Hawthorn Red', 'TREES', 'Color that has never been seen before in a selection of our beautiful native Eastern Redbud, until now.  This is one of the most exciting Redbud trees ever to be introduced to home gardeners\r\n\r\nFiery Summer Foliage: Experience a blaze of glory as the heart-shaped leaves transition through a kaleidoscope of burgundy, red, tangerine-orange and yellow-gold. New and unique, this fiery display creates a stunning visual impact in your yard, making Hearts A\'Fire™ Redbud a focal point of admiration and wonder.\r\n\r\nSpring Splendor: As the season awakens, it bursts into life with clusters of deep pink flowers. These blossoms are a feast for the eyes and a haven for butterflies and pollinators, infusing your garden with life and color.\r\n\r\nWinter Charm: Even in its leafless winter state, Hearts A\'Fire™ continues to enchant. Winter-time seed pods of this native selection provide sustenance to several species of songbirds, adding exciting activity to your garden during colder months.\r\n\r\nHarmonious Fall Transition: As summer fades, the foliage matures into a mix of reddish to green tones, offering a soothing and harmonious transition into fall. This tree\'s ability to evolve with the seasons brings a dynamic and ever-changing beauty to your garden.\r\n\r\nCERCIS CANADENSIS \'JN100\' PPAF', 521500, 9, 0x6173736574732f696d672f4365726369735f486561727473415f666972655f312e77656270),
(80, 'Cascadia Ruffle Tree Maple', 'TREES', 'A Living Sculpture: Cascadia Maple, a product of the renowned Iseli Nursery\'s expertise in tree breeding, is more than just a tree—it is a piece of living art. With its sculptural arms and multi-dimensional leaves, it brings an unparalleled aesthetic to any garden. The beautifully divided, cut-leaf foliage emerges in early spring, creating a vibrant display that remains bright and lively throughout the summer. \r\n\r\nStunning Foliage Through the Seasons: One of Cascadia’s most captivating features is its ability to transform with the seasons. In autumn, its foliage shifts to a stunning yellow-orange hue, providing your garden with a warm and inviting atmosphere. This seasonal change ensures that your garden remains visually interesting and beautiful all year long. \r\n\r\nPerfect for Any Garden Space: Cascadia\'s compact size, reaching only 7–10\' tall, makes it an ideal choice for various garden spaces. Whether you are looking to provide ambiance to a summertime reading nook or fill in a sunny or partially shaded border, this maple fits perfectly. Its elegant shape and cascading habit add a touch of sophistication to any area, without overwhelming the space. \r\n\r\nLow-Maintenance Beauty: This tree pairs the best of its Korean heritage with hardiness that allows it to thrive in U.S. climates. Rarely requiring pruning, it is a low-maintenance option for gardeners who want to enjoy its color and beauty without the hassle. Its effortless elegance and resilience make it a practical and attractive choice for any landscape. \r\n\r\nAcer x pseudosieboldianum \'Cascadia\'', 521500, 21, 0x6173736574732f696d672f38313732342e77656270),
(81, 'Norway Dogwood Spruce', 'TREES', 'The Norway Spruce originates from parts of Eastern Europe and the Black Forest. As Europeans emigrated from the Old Country, so did this beautiful conifer—and we\'re so glad it\'s part of American landscapes today. An attractive, broad tree with a perfect pyramidal shape, the Norway Spruce is a Christmas favorite. The Norway Spruce grows rapidly, with the ability to reach heights over one hundred feet, but will typically grow between forty and sixty feet in cool and temperate climates. Due to its stature, this Norway Spruce works well as a privacy border or windscreen. If you\'re just looking for a statement evergreen tree, the Norway Spruce can serve as a lovely standalone, too.\r\n\r\nNorway Spruces are also a hardy option for your landscape and can withstand snowfall and temperatures of up to -30 degrees fahrenheit. Thanks to their drought tolerance and resistance to disease, Norway Spruce trees can thrive for centuries. In addition to being an attractive evergreen presence in your landscape, the Norway Spruce tree even attracts wild songbirds.\r\n\r\nIf you\'re ready to take home this conifer today, be sure to check out our trees and shrubs planting guide!', 241500, 31, 0x6173736574732f696d672f3832383739412e77656270),
(83, 'Coral Bark Japanese Maple', 'TREES', 'The Coral Bark Japanese Maple, known for its striking and vivid presence through all four seasons, offers an unmatched visual delight in any garden setting. This ornamental tree is not just a plant but a year-round spectacle that brings joy and color to your landscape.\r\n\r\nStriking Red Bark Brightens Winter Scenery:  During the colder months, the Coral Bark Japanese Maple transforms into a striking showcase, with its bark turning a fiery red that stands out against the dull hues of winter. This unique feature ensures that your garden retains a burst of color even in the most barren season, making it a standout addition to any landscape.\r\n\r\nLush, Deeply Cut Leaves Provide Textural Contrast:  As the seasons change, so does the foliage of the Coral Bark Japanese Maple. Its deeply dissected leaves offer a sophisticated texture, creating a dense canopy of green that shifts to a vibrant gold-yellow in the fall. This transition not only enhances the autumn landscape but also adds a level of depth and intricacy to your garden design.\r\n\r\nLow Maintenance, High Impact:  Not only does the Coral Bark Japanese Maple bring stunning colors and textures to your garden, but once established it also thrives with minimal care. This tree is adaptable to various climates and soil types, requiring only basic upkeep to maintain its health and vibrant appearance. It’s the perfect choice for anyone looking to add lasting beauty to their outdoor space without the hassle of intensive gardening.', 3500, 55, 0x6173736574732f696d672f39343234342e77656270),
(84, 'Royal Purple Smoke Tree', 'TREES', 'Draw the eye to this focal point in regal hues. Royal Purple Smoketree was first introduced from Holland in the 1950s, and has been a favorite specimen plant ever since, thanks to its colorful foliage and airy seed clusters. This stunning shrub commands attention, even when you provide it with little care.. Small flowers appear in spring, then mature into feathery, wine-red plumes. Amazing foliage all year, in regal tones of purple and maroon, gives this plant true multi-season \"wow\" factor. Use this as an accent shrub, and don\'t be surprised when you find yourself planning the entire landscape around this beautiful plant. Cotinus coggygria \'Royal Purple\'', 136500, 44, 0x6173736574732f696d672f3739313935412e77656270);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(30) NOT NULL,
  `age` int(11) NOT NULL,
  `email` varchar(50) NOT NULL,
  `address` varchar(30) NOT NULL,
  `password` varchar(20) NOT NULL,
  `gender` varchar(11) NOT NULL,
  `role` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `age`, `email`, `address`, `password`, `gender`, `role`) VALUES
(1, 'Nyan Min Htet', 20, 'nhtet9968@gmail.com', 'Ahlone', '1234', 'male', 'admin'),
(2, 'Yan Yan', 20, 'yanyan@gmail.com', 'Ahlone', '5678', 'male', 'user'),
(3, 'Shine Thuya', 20, 'koshine@email.com', 'Sanchaung', '34789', 'male', 'admin'),
(4, 'Bhone Myat Thein', 20, 'bhone@email.com', 'Mandalay', '5689', 'male', 'user'),
(5, 'Yuya Koko', 20, 'yuya@email.com', 'Mingaladon', '93456', 'female', 'user'),
(7, 'May Myat Noe', 18, 'may345@email.com', 'Ahlone', '89456', 'female', 'admin'),
(8, 'Htay Htay', 28, 'htayhtay89@email.com', 'Yangon', '4634567', 'female', 'user'),
(9, 'Ko Luu Aye', 25, 'luuaye45@email.com', 'Thamine', '23456765', 'male', 'user'),
(10, 'Thaw Tar', 19, 'thawtar56@email.com', 'Bahan', '65423', 'female', 'user'),
(11, 'Ye Win Thu', 20, 'koye123@email.com', 'North Oakkala', '12345', 'male', 'user');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `flower_product`
--
ALTER TABLE `flower_product`
  ADD PRIMARY KEY (`product_id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `flower_product`
--
ALTER TABLE `flower_product`
  MODIFY `product_id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=85;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
